### ISSUE TITLE
Crash when quiting minecraft

### ISSUE THREAD

**Issue by Furionstrom** [CrankySupertoon01/Rebirth-3#20]
Every time when exiting minecraft the modpack crashes, it is more an annoyance then anything as it is when exiting anyway but the following is output in the log:

Exception in thread "Airbush Recipe Scanner" 
Process crashed with exitcode -1073740791.

**Comment by CrankySupertoon01** [comment]
Can you explain more info, this doesnt seem like a issue any of my testers have found

**Comment by Furionstrom** [comment]
It may just be a multimc thing, as it shows when a previous instance crashes.  However, when exiting minecraft it appears to hang a second then exits to the desktop with the multiMC log showing that minecraft crashed.

**Comment by Furionstrom** [comment]
As i said it is more of an annoyance, especially if no one else is seeing the issue

**Comment by CrankySupertoon01** [comment]
Im Going to Close this for now. If this comes up just make another issue report
