### ISSUE TITLE
"Wearing Wood" Crafting conflict for "Wooden Boots"

### ISSUE THREAD

**Issue by ParadoxedHope** [CrankySupertoon01/Rebirth-3#61]
The Quest "Wearing Wood", requires a full set of Wooden armour. The Wooden Boots (Tiny Progressions) recipe is conflicting with a crafting recipe for "Log Pile" (Forestry,) possibly this recipe isn't meant to be shapeless.

![2018-10-15_00 04 43](https://user-images.githubusercontent.com/37836439/46923370-96079900-d00e-11e8-9da3-fc67856a27cf.png)

The results were the same for both Oak and Dark Oak logs, no others tested.

**Comment by CrankySupertoon01** [comment]
in dev
